resource_name :osl_shell_environment
provides :osl_shell_environment
unified_mode true

default_action :add

property :environment_variable, String, name_property: true
property :value, String, required: [:add]
property :owner, String, default: 'root'
property :group, String, default: 'root'
property :mode, String, default: '0644'
property :destination, String, default: '/etc/profile.d'

action :add do
  file destination do
    owner new_resource.owner
    group new_resource.group
    mode new_resource.mode
    sensitive new_resource.sensitive
    content <<-EOF.gsub(/^ {6}/, '')
      #
      # This file was generated by Chef
      # Do NOT modify this file by hand!
      #
      export #{new_resource.environment_variable}="#{new_resource.value}"
    EOF
  end
end

action :remove do
  file destination do
    action :delete
  end
end

action_class do
  def destination
    "#{new_resource.destination}/#{filename}.sh"
  end

  def filename
    new_resource.environment_variable.to_s.gsub(/\s/, '_')
  end
end
