resource_name :osl_shell_function
provides :osl_shell_function
unified_mode true

default_action :add

property :body, String, required: [:add],
  description: 'The body of the shell function. Use "$@" to pass through all arguments.'
property :function_name, String, name_property: true

action :add do
  file destination do
    mode '0755'
    content <<~EOF
      #
      # This file was generated by Chef
      # Do NOT modify this file by hand!
      #
      #{new_resource.function_name}() {
        #{new_resource.body}
      }
    EOF
  end
end

action :remove do
  file destination do
    action :delete
  end
end

action_class do
  def destination
    "/etc/profile.d/#{filename}.sh"
  end

  def filename
    new_resource.function_name.to_s.gsub(/\s/, '_')
  end
end
