resource_name :osl_caddy_site
provides :osl_caddy_site
default_action :create
unified_mode true

property :site_name, String, name_property: true
property :content, [String, Hash], required: true

action :create do
  if new_resource.content.is_a?(String)
    file "/etc/caddy/sites/#{new_resource.site_name}.caddyfile" do
      content "# This file was generated by Chef Infra\n# Do NOT modify this file by hand.\n#{new_resource.content}"
    end
  elsif new_resource.content.is_a?(Hash)
    template "/etc/caddy/sites/#{new_resource.site_name}.caddyfile" do
      cookbook 'osl-resources'
      source 'Caddyfile-site.erb'
      variables(content: render_caddy_site_from_hash(new_resource.content))
    end
  else
    raise ArgumentError, "osl_caddy_site resource's 'content' property must be a String or a Hash."
  end
end

action :delete do
  file "/etc/caddy/sites/#{new_resource.site_name}.caddyfile" do
    action :delete
  end
end
