require 'spec_helper'

describe 'osl_shell_function' do
  recipe do
    osl_shell_function 'pcp_node_info' do
      body '/usr/bin/pcp_node_info -h localhost -p 9898 -U pgpool -w "$@"'
    end

    osl_shell_function 'remove' do
      action :remove
    end
  end

  context 'almalinux' do
    platform 'almalinux'
    cached(:subject) { chef_run }
    step_into :osl_shell_function

    it do
      is_expected.to create_file('/etc/profile.d/pcp_node_info.sh')
        .with(
          mode: '0755',
          content: <<~EOF
            #
            # This file was generated by Chef
            # Do NOT modify this file by hand!
            #
            pcp_node_info() {
              /usr/bin/pcp_node_info -h localhost -p 9898 -U pgpool -w "$@"
            }
          EOF
        )
    end
    it do
      is_expected.to delete_file('/etc/profile.d/remove.sh')
    end
  end
end
