control 'osl_geoip' do
  describe package 'geoipupdate' do
    it { should be_installed }
  end

  describe command 'geoipupdate -V' do
    its('exit_status') { should eq 0 }
  end

  describe file '/etc/GeoIP.conf' do
    its('mode') { should cmp '0640' }
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.
        AccountID 10000
        LicenseKey fake-key
        EditionIDs GeoLite2-ASN GeoLite2-City GeoLite2-Country
      EOF
    end
  end

  describe file '/etc/cron.d/geoipupdate' do
    its('content') { should match %r{@weekly root /usr/bin/geoipupdate > /dev/null} }
  end
end
