# osl_anubis denies these by default (osl_anubis_stale_browser_user_agents)
stale_uas = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0',
]
# The rendered regex, spelt out rather than rebuilt with the helper's escaping
stale_re = '^(' + [
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/118\.0\.0\.0 Safari/537\.36',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/119\.0\.0\.0 Safari/537\.36',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/119\.0\.0\.0 Safari/537\.36 Edg/119\.0\.0\.0',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/120\.0\.0\.0 Safari/537\.36',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/120\.0\.0\.0 Safari/537\.36 Edg/120\.0\.0\.0',
  'Mozilla/5\.0 \(Macintosh; Intel Mac OS X 10_15_7\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/119\.0\.0\.0 Safari/537\.36',
  'Mozilla/5\.0 \(Macintosh; Intel Mac OS X 10_15_7\) AppleWebKit/537\.36 \(KHTML, like Gecko\) Chrome/120\.0\.0\.0 Safari/537\.36',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64; rv:120\.0\) Gecko/20100101 Firefox/120\.0',
  'Mozilla/5\.0 \(Windows NT 10\.0; Win64; x64; rv:121\.0\) Gecko/20100101 Firefox/121\.0',
  'Mozilla/5\.0 \(Macintosh; Intel Mac OS X 10\.15; rv:121\.0\) Gecko/20100101 Firefox/121\.0',
].join('|') + ')$'

control 'osl_anubis' do
  describe package 'anubis' do
    it { should be_installed }
  end

  # The resource sets GOMEMLIMIT to half the host's RAM
  memory_limit = "#{command("awk '/MemTotal/ {print $2}' /proc/meminfo").stdout.to_i / 2048}MiB"

  # valkey ships in AppStream from EL 9.7; before that the store stays bbolt
  valkey = os.redhat? && Gem::Version.new(os.release) >= Gem::Version.new('9.7')

  describe file '/etc/anubis/default.env' do
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    its('mode') { should cmp '0600' }
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.
        BIND=127.0.0.1:8932
        METRICS_BIND=:9090
        SERVE_ROBOTS_TXT=false
        BIND_NETWORK=tcp
        COOKIE_EXPIRATION_TIME=168h
        COOKIE_PARTITIONED=true
        ED25519_PRIVATE_KEY_HEX=4f2b8c1d9e3a7056b4c8d2f1a903e5b7c6d4082f1e9a3b5c7d08f2a4e6b1c3d5
        POLICY_FNAME=/etc/anubis/botPolicies-default.yaml
        TARGET=http://127.0.0.1:8080
        GOMEMLIMIT=#{memory_limit}
        SLOG_LEVEL=DEBUG
      EOF
    end
  end

  describe file '/etc/anubis/botPolicies-default.yaml' do
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.

        bots:
          - import: (data)/bots/_deny-pathological.yaml
          - import: (data)/bots/aggressive-brazilian-scrapers.yaml
          - import: (data)/meta/ai-block-aggressive.yaml
          - import: (data)/crawlers/_allow-good.yaml
          - import: (data)/clients/x-firefox-ai.yaml
          - import: (data)/crawlers/xai.yaml
          - import: (data)/common/keep-internet-working.yaml

          # deny_user_agents: exact user agents, denied before any other rule
          - name: deny-user-agents
            user_agent_regex: >-
              #{stale_re}
            action: DENY

          # Custom bots
          - name: static-assets
            path_regex: "^/assets/.*$"
            action: ALLOW

          # Generic catchall rule
          - name: generic-browser
            user_agent_regex: >-
              Mozilla|Opera
            action: WEIGH
            weight:
              adjust: 10

        thresholds:
          - name: default-challenge
            expression: weight > 0
            action: CHALLENGE
            challenge:
              algorithm: fast
              difficulty: 3

        dnsbl: false

        # Extra config
        store:
          backend: memory
          parameters: {}
      EOF
    end
  end

  # Explicit key, converged to the value the resource was given. 0600 root:root
  # is fine because only Chef reads this file; anubis gets the key via the env.
  describe file '/etc/anubis/default.key' do
    it { should be_owned_by 'root' }
    its('mode') { should cmp '0600' }
    its('content') { should cmp '4f2b8c1d9e3a7056b4c8d2f1a903e5b7c6d4082f1e9a3b5c7d08f2a4e6b1c3d5' }
  end

  # Generated on first run; kitchen's enforce_idempotency proves it is stable
  describe file '/etc/anubis/generated.key' do
    it { should be_owned_by 'root' }
    its('mode') { should cmp '0600' }
    its('content') { should match(/\A[0-9a-f]{64}\Z/) }
  end

  describe service 'anubis@default.service' do
    it { should be_enabled }
    it { should be_running }
  end

  # systemd owns the runtime directory via RuntimeDirectory=anubis/%i
  describe directory '/run/anubis/default' do
    it { should exist }
  end

  describe port 8932 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should cmp '127.0.0.1' }
  end

  # nginx reverse proxy in front of Anubis
  describe port 80 do
    it { should be_listening }
    its('processes') { should cmp 'nginx' }
  end

  # A challenge through nginx, which sets X-Real-IP, so the counters have samples.
  # --compressed: anubis 500s one in 64 challenges to clients that don't accept gzip.
  challenge = command("curl -s --compressed -w '\\n%{http_code}' -H 'User-Agent: Mozilla/5.0' " \
                      "-H 'Host: anubis-test' http://127.0.0.1/")

  describe challenge do
    its('stdout') { should match(/\n200\z/) }
  end

  # Test that the challenge page includes the correct difficulty via nginx proxy
  describe json(content: challenge.stdout.match(/id="anubis_challenge"[^>]*>([^<]+)</)[1]) do
    its(%w(rules difficulty)) { should eq 3 }
  end

  # Metrics listen on all interfaces so Prometheus can scrape them remotely
  describe port 9090 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should include '0.0.0.0' }
  end

  describe http('http://127.0.0.1:9090/metrics') do
    its('status') { should cmp 200 }
    its('body') { should match(/^anubis_challenges_issued/) }
    its('body') { should match(%r{^anubis_policy_results.*rule="threshold/default-challenge"}) }
  end

  describe http('http://127.0.0.1:9090/healthz') do
    its('status') { should cmp 200 }
  end

  # ...but only OSL-managed ranges are allowed to reach them
  describe command('iptables -S anubis-metrics-default') do
    its('exit_status') { should eq 0 }
    its('stdout') { should match(/--dport 9090 -j osl_only/) }
  end

  # Second instance: its own key, ports, policy and firewall rule
  describe file '/etc/anubis/generated.env' do
    its('mode') { should cmp '0600' }
    its('content') { should match(/^BIND=127\.0\.0\.1:8933$/) }
    its('content') { should match(/^METRICS_BIND=:9091$/) }
    its('content') { should match(%r{^POLICY_FNAME=/etc/anubis/botPolicies-generated\.yaml$}) }
    its('content') { should match(/^REDIRECT_DOMAINS=anubis-test$/) }
    # The generated key is handed over inline; DynamicUser cannot read a file
    its('content') { should match(/^ED25519_PRIVATE_KEY_HEX=[0-9a-f]{64}$/) }
    its('content') { should match(/^GOMEMLIMIT=#{memory_limit}$/) }
    # This instance sets no extra_env, so it gets the resource's quieter default
    its('content') { should match(/^SLOG_LEVEL=WARN$/) }
  end

  # The first instance above overrides the store with the memory backend
  # through extra_config; this one takes the resource's default.
  if valkey
    describe file '/etc/anubis/botPolicies-generated.yaml' do
      its('content') { should match(%r{^store:\n  backend: valkey\n  parameters:\n    url: redis://127\.0\.0\.1:6390/0$}) }
      its('content') { should_not match(/# Extra config/) }
    end

    describe service 'valkey@anubis' do
      it { should be_enabled }
      it { should be_running }
    end

    describe command 'systemctl show -p Restart valkey@anubis.service' do
      its('stdout') { should eq "Restart=on-failure\n" }
    end

    describe command 'systemctl show -p After -p Wants anubis@generated.service' do
      its('stdout') { should match(/^After=.*\bvalkey@anubis\.service\b/) }
      its('stdout') { should match(/^Wants=.*\bvalkey@anubis\.service\b/) }
    end

    describe port 6390 do
      it { should be_listening }
      its('addresses') { should eq ['127.0.0.1'] }
    end

    # Nothing here forks, so the packaged server and overcommit stay untouched
    describe service 'valkey' do
      it { should_not be_running }
    end

    describe file '/etc/sysctl.d/99-chef-vm.overcommit_memory.conf' do
      it { should_not exist }
    end

    {
      'save' => '',
      'maxmemory' => '2147483648',
      'maxmemory-policy' => 'allkeys-lru',
    }.each do |key, value|
      describe command "valkey-cli -p 6390 CONFIG GET #{key}" do
        its('stdout') { should eq "#{key}\n#{value}\n" }
      end
    end

    describe file '/var/lib/anubis/generated/anubis.bdb' do
      it { should_not exist }
    end
  else
    describe file '/etc/anubis/botPolicies-generated.yaml' do
      its('content') { should match(%r{^store:\n  backend: bbolt\n  parameters:\n    path: "?/var/lib/anubis/generated/anubis\.bdb"?$}) }
      its('content') { should_not match(/# Extra config/) }
    end

    # anubis creates the database when it opens the store at start
    describe file '/var/lib/anubis/generated/anubis.bdb' do
      it { should exist }
      its('size') { should be > 0 }
    end
  end

  # The env file and the persisted key file must agree, or a restart would
  # invalidate every cookie anubis has already issued
  describe command('grep -oP "(?<=^ED25519_PRIVATE_KEY_HEX=).*" /etc/anubis/generated.env') do
    its('stdout.strip') { should cmp file('/etc/anubis/generated.key').content.strip }
  end

  describe service 'anubis@generated.service' do
    it { should be_enabled }
    it { should be_running }
  end

  describe directory '/run/anubis/generated' do
    it { should exist }
  end

  describe port 8933 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should cmp '127.0.0.1' }
  end

  describe port 9091 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should include '0.0.0.0' }
  end

  # A challenge so this instance exports metrics; nothing proxies it, so send X-Real-IP.
  # --compressed: anubis 500s one in 64 challenges to clients that don't accept gzip.
  describe command("curl -s --compressed -w '\\n%{http_code}' -H 'User-Agent: Mozilla/5.0' " \
                   "-H 'Host: anubis-test' -H 'X-Real-IP: 127.0.0.1' http://127.0.0.1:8933/") do
    its('stdout') { should match(/\n200\z/) }
    its('stdout') { should match(%r{id="anubis_challenge" type="application/json">\{}) }
  end

  # DENY answers 200 with the "Oh noes!" page and an empty challenge; the counter proves the rule
  describe http('http://127.0.0.1:8933/',
                headers: {
                  'User-Agent' => stale_uas.first,
                  'Host' => 'anubis-test',
                  'X-Real-IP' => '127.0.0.1',
                }) do
    its('body') { should match(%r{<title>Oh noes!</title>}) }
    its('body') { should match(%r{id="anubis_challenge" type="application/json">null}) }
  end

  # End to end: that challenge is now held in valkey, not on disk
  if valkey
    describe command "valkey-cli -p 6390 --scan --pattern 'challenge:*'" do
      its('stdout') { should_not be_empty }
    end
  end

  # Each instance exports on the port it registers for prometheus to discover,
  # so both are scraped independently rather than one standing in for the other.
  describe http('http://127.0.0.1:9091/metrics') do
    its('status') { should cmp 200 }
    its('body') { should match(/^anubis_challenges_issued/) }
    its('body') { should match(/^anubis_policy_results\{action="DENY",[^}]*rule="bot\/deny-user-agents"\} [1-9]/) }
  end

  describe http('http://127.0.0.1:9091/healthz') do
    its('status') { should cmp 200 }
  end

  describe command('iptables -S anubis-metrics-generated') do
    its('exit_status') { should eq 0 }
    its('stdout') { should match(/--dport 9091 -j osl_only/) }
  end
end
