control 'osl_anubis' do
  describe package 'anubis' do
    it { should be_installed }
  end

  describe file '/etc/anubis/default.env' do
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    its('mode') { should cmp '0600' }
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.
        BIND=127.0.0.1:8932
        METRICS_BIND=:9090
        SERVE_ROBOTS_TXT=false
        BIND_NETWORK=tcp
        COOKIE_EXPIRATION_TIME=168h
        COOKIE_PARTITIONED=true
        ED25519_PRIVATE_KEY_HEX=4f2b8c1d9e3a7056b4c8d2f1a903e5b7c6d4082f1e9a3b5c7d08f2a4e6b1c3d5
        POLICY_FNAME=/etc/anubis/botPolicies-default.yaml
        TARGET=http://127.0.0.1:8080
        SLOG_LEVEL=DEBUG
      EOF
    end
  end

  describe file '/etc/anubis/botPolicies-default.yaml' do
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.

        bots:
          - import: (data)/bots/_deny-pathological.yaml
          - import: (data)/bots/aggressive-brazilian-scrapers.yaml
          - import: (data)/meta/ai-block-aggressive.yaml
          - import: (data)/crawlers/_allow-good.yaml
          - import: (data)/clients/x-firefox-ai.yaml
          - import: (data)/crawlers/xai.yaml
          - import: (data)/common/keep-internet-working.yaml

          # Custom bots
          - name: static-assets
            path_regex: "^/assets/.*$"
            action: ALLOW

          # Generic catchall rule
          - name: generic-browser
            user_agent_regex: >-
              Mozilla|Opera
            action: WEIGH
            weight:
              adjust: 10

        thresholds:
          - name: default-challenge
            expression: weight > 0
            action: CHALLENGE
            challenge:
              algorithm: fast
              difficulty: 3

        dnsbl: false

        # Extra config
        store:
          backend: memory
          parameters: {}
      EOF
    end
  end

  # Explicit key, converged to the value the resource was given. 0600 root:root
  # is fine because only Chef reads this file; anubis gets the key via the env.
  describe file '/etc/anubis/default.key' do
    it { should be_owned_by 'root' }
    its('mode') { should cmp '0600' }
    its('content') { should cmp '4f2b8c1d9e3a7056b4c8d2f1a903e5b7c6d4082f1e9a3b5c7d08f2a4e6b1c3d5' }
  end

  # Generated on first run; kitchen's enforce_idempotency proves it is stable
  describe file '/etc/anubis/generated.key' do
    it { should be_owned_by 'root' }
    its('mode') { should cmp '0600' }
    its('content') { should match(/\A[0-9a-f]{64}\Z/) }
  end

  describe service 'anubis@default.service' do
    it { should be_enabled }
    it { should be_running }
  end

  # systemd owns the runtime directory via RuntimeDirectory=anubis/%i
  describe directory '/run/anubis/default' do
    it { should exist }
  end

  describe port 8932 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should cmp '127.0.0.1' }
  end

  # nginx reverse proxy in front of Anubis
  describe port 80 do
    it { should be_listening }
    its('processes') { should cmp 'nginx' }
  end

  # Drive a challenge before scraping, so the counters have samples to export.
  # nginx sets X-Real-IP; without it anubis rejects every request.
  challenge = http('http://127.0.0.1/', headers: { 'User-Agent' => 'Mozilla/5.0', 'Host' => 'anubis-test' })

  describe challenge do
    its('status') { should cmp 200 }
  end

  # Test that the challenge page includes the correct difficulty via nginx proxy
  describe json(content: challenge.body.match(/id="anubis_challenge"[^>]*>([^<]+)</)[1]) do
    its(%w(rules difficulty)) { should eq 3 }
  end

  # Metrics listen on all interfaces so Prometheus can scrape them remotely
  describe port 9090 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should include '0.0.0.0' }
  end

  describe http('http://127.0.0.1:9090/metrics') do
    its('status') { should cmp 200 }
    its('body') { should match(/^anubis_challenges_issued/) }
    its('body') { should match(%r{^anubis_policy_results.*rule="threshold/default-challenge"}) }
  end

  describe http('http://127.0.0.1:9090/healthz') do
    its('status') { should cmp 200 }
  end

  # ...but only OSL-managed ranges are allowed to reach them
  describe command('iptables -S anubis-metrics-default') do
    its('exit_status') { should eq 0 }
    its('stdout') { should match(/--dport 9090 -j osl_only/) }
  end

  # Second instance: its own key, ports, policy and firewall rule
  describe file '/etc/anubis/generated.env' do
    its('mode') { should cmp '0600' }
    its('content') { should match(/^BIND=127\.0\.0\.1:8933$/) }
    its('content') { should match(/^METRICS_BIND=:9091$/) }
    its('content') { should match(%r{^POLICY_FNAME=/etc/anubis/botPolicies-generated\.yaml$}) }
    its('content') { should match(/^REDIRECT_DOMAINS=anubis-test$/) }
    # The generated key is handed over inline; DynamicUser cannot read a file
    its('content') { should match(/^ED25519_PRIVATE_KEY_HEX=[0-9a-f]{64}$/) }
  end

  # The env file and the persisted key file must agree, or a restart would
  # invalidate every cookie anubis has already issued
  describe command('grep -oP "(?<=^ED25519_PRIVATE_KEY_HEX=).*" /etc/anubis/generated.env') do
    its('stdout.strip') { should cmp file('/etc/anubis/generated.key').content.strip }
  end

  describe service 'anubis@generated.service' do
    it { should be_enabled }
    it { should be_running }
  end

  describe directory '/run/anubis/generated' do
    it { should exist }
  end

  describe port 8933 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should cmp '127.0.0.1' }
  end

  describe port 9091 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should include '0.0.0.0' }
  end

  describe command('iptables -S anubis-metrics-generated') do
    its('exit_status') { should eq 0 }
    its('stdout') { should match(/--dport 9091 -j osl_only/) }
  end
end
