control 'osl_anubis' do
  describe package 'anubis' do
    it { should be_installed }
  end

  describe file '/etc/anubis/default.env' do
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.
        BIND=127.0.0.1:8932
        METRICS_BIND=:9090
        SERVE_ROBOTS_TXT=false
        BIND_NETWORK=tcp
        COOKIE_EXPIRATION_TIME=168h
        COOKIE_PARTITIONED=false
        POLICY_FNAME=/etc/anubis/botPolicies-default.yaml
        TARGET=http://127.0.0.1:8080
      EOF
    end
  end

  describe file '/etc/anubis/botPolicies-default.yaml' do
    its('content') do
      should cmp <<~EOF
        # This file was generated by Chef Infra
        # Do NOT modify this file by hand.

        bots:
          - import: (data)/bots/_deny-pathological.yaml
          - import: (data)/bots/aggressive-brazilian-scrapers.yaml
          - import: (data)/meta/ai-block-aggressive.yaml
          - import: (data)/crawlers/_allow-good.yaml
          - import: (data)/clients/x-firefox-ai.yaml
          - import: (data)/common/keep-internet-working.yaml

          # Custom bots
          - name: static-assets
            path_regex: "^/assets/.*$"
            action: ALLOW

          # Generic catchall rule
          - name: generic-browser
            user_agent_regex: >-
              Mozilla|Opera
            action: WEIGH
            weight:
              adjust: 10

        thresholds:
          - name: default-challenge
            expression: weight > 0
            action: CHALLENGE
            challenge:
              algorithm: fast
              difficulty: 3

        dnsbl: false

        # Extra config
        store:
          backend: memory
          parameters: {}
      EOF
    end
  end

  describe service 'anubis@default.service' do
    it { should be_enabled }
    it { should be_running }
  end

  describe port 8932 do
    it { should be_listening }
    its('processes') { should cmp 'anubis' }
    its('addresses') { should cmp '127.0.0.1' }
  end

  # nginx reverse proxy in front of Anubis
  describe port 80 do
    it { should be_listening }
    its('processes') { should cmp 'nginx' }
  end

  # Test that the challenge page includes the correct difficulty via nginx proxy
  describe json(content: http('http://127.0.0.1/', headers: { 'User-Agent' => 'Mozilla/5.0', 'Host' => 'anubis-test' }).body.match(/id="anubis_challenge"[^>]*>([^<]+)</)[1]) do
    its(%w(rules difficulty)) { should eq 3 }
  end
end
